image: node:18

stages:
  - build
  - deploy
  - mirror

build:
  stage: build
  variables:
    PUBLIC_URL: /sushi-lover
  script:
    - cd fresh-fusion
    - npm install
    - npm run build
  tags:
    - general
  artifacts:
    paths:
      - fresh-fusion/build/

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - rm -rf public
    - mkdir public
    - cp -r fresh-fusion/build/* public/
  tags:
    - general
  artifacts:
    paths:
      - public
  only:
    - main

mirror_to_github:
  stage: mirror
  image: alpine:latest
  before_script:
    - apk add --no-cache git openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo "Host github.com" > ~/.ssh/config
    - echo "  StrictHostKeyChecking no" >> ~/.ssh/config
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    - cd fresh-fusion-backend
    - git init
    - git add .
    - git commit -m "Update backend"
    - git remote add github git@github.com:lachesism0609/fresh-fusion-backend.git
    - git push -f github main
  only:
    - main
  variables:
    GIT_STRATEGY: clone

