# The Docker image that will be used to build your app
image: node:latest
# Functions that should be executed before the build script is run
before_script:
  - cd fresh-fusion
  - npm install --save-dev @babel/plugin-proposal-private-property-in-object
  - npm install
  - npm run build
  - mkdir -p ../public
  - cp -r build/* ../public/
pages:
  tags:
    - docker
    - general
  script:
    - ls -la public/
    - echo 'Deploy to GitLab Pages'
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
