image: node:18

stages:
  - build
  - deploy
  - mirror

build:
  stage: build
  variables:
    PUBLIC_URL: /sushi-lover
  script:
    - cd fresh-fusion
    - npm install
    - npm run build
  tags:
    - general
  artifacts:
    paths:
      - fresh-fusion/build/

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - rm -rf public
    - mkdir public
    - cp -r fresh-fusion/build/* public/
  tags:
    - general
  artifacts:
    paths:
      - public
  only:
    - main

mirror_to_github:
  stage: mirror
  image: alpine:latest
  before_script:
    - apk add --no-cache git
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    # Clone the repository
    - cd fresh-fusion-backend
    - git remote add github https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/${GITHUB_REPO}.git
    - git push --mirror github
  only:
    - main
  variables:
    GIT_STRATEGY: clone

