image: node:latest

before_script:
  - cd fresh-fusion
  - npm install
  - npm run build
  - mkdir -p ../public
  - cp -r build/* ../public/

pages:
  tags:
    - docker
    - genneral
  script:
    - ls -la public/
    - echo 'Deploy to GitLab Pages'
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH