# The Docker image that will be used to build your app
image: node:latest

variables:
  NPM_CONFIG_CACHE: ".npm"

cache:
  paths:
    - fresh-fusion-test/node_modules/
    - .npm/

pages:
  tags:
    - docker
    - general
  script:
    - cd fresh-fusion-test
    
    # Install dependencies
    - rm -rf node_modules package-lock.json
    - npm install
    
    # Build with environment variables
    - NODE_ENV=production CI=false npm run build
    
    # Move build files
    - cd ..
    - mkdir -p public
    - cp -r fresh-fusion-test/build/* public/
  
  artifacts:
    paths:
      - public
    when: always
  
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH