image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - fresh-fusion/node_modules/

build:
  stage: build
  script:
    - cd fresh-fusion
    - npm install
    - npm run build
    - mkdir -p ../public
    - cp -r build/* ../public/
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - echo 'Deploy to GitLab Pages'
  artifacts:
    paths:
      - public
  only:
    - master