# The Docker image that will be used to build your app
image: node:latest

variables:
  NPM_CONFIG_CACHE: ".npm"

cache:
  paths:
    - .npm/
    - fresh-fusion/node_modules/

pages:
  tags:
    - docker
    - general
  script:
    - cd fresh-fusion
    - rm -rf node_modules package-lock.json
    - npm cache clean --force
    - npm install --no-optional
    - CI=false npm run build
    - mkdir -p ../public
    - cp -r build/* ../public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
