image: node:latest 

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build
    - cp -r build/* public/
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - echo 'Deploy to GitLab Pages'
  artifacts:
    paths:
      - public
  only:
    - master