services:
  - type: web
    name: fresh-fusion-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: "https://ae8278.pages.labranet.jamk.fi/sushi-lover"
    autoDeploy: true