### 5. Test Create Menu
POST http://localhost:5000/api/menu/createMenu
Content-Type: application/json


{
  "name": "California Roll",
  "category": "Sushi",
  "price": 12.99,
  "description": "A popular sushi roll with crab, avocado, and cucumber.",
  "imageURL": "https://example.com/images/california_roll.jpg",
  "dietaryFlags": ["gluten-free", "dairy-free"]
}

### 4. Test Get All Menu - Public Route (no authentication required)
### tocken = '9a3fad9ca9b6603d0e27b01a67ec1832a4105560fc5a67c0016fa17758fb00c29a96c0a99b5e013f2c7df9ac8f5afcc16e4fb08d685e67c641ef0e5fec564e8d'
GET http://localhost:5000/api/menu/

