name: Deploy to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push to the main branch
  push:
    branches: [ "main" ]
  # Allows manual triggering from the Actions tab
  workflow_dispatch:

# Set permissions for GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write

# Only allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './fresh-fusion/package-lock.json'
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Install dependencies
        run: |
          cd fresh-fusion
          npm install
      
      - name: Build
        run: |
          cd fresh-fusion
          CI=false npm run build
        env:
          PUBLIC_URL: /fresh-fusion
          
      - name: Create .nojekyll file
        run: |
          touch fresh-fusion/build/.nojekyll
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './fresh-fusion/build'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
